stages:

  data_ingestion:

    cmd: python src/DeepfakeDetection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_01_data_ingestion.py
      - src/DeepfakeDetection/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data


  data_preprocessing:

    cmd: python src/DeepfakeDetection/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_02_data_preprocessing.py
      - src/DeepfakeDetection/components/data_preprocessing.py
      - config/config.yaml
      - artifacts/data_ingestion/data
    params:
      - max_frames
      - fps
      - resolution
      - expansion_factor
    outs:
      - artifacts/data_preprocessing/train
      - artifacts/data_preprocessing/test
      - artifacts/data_preprocessing/val


  model_training:

    cmd: python src/DeepfakeDetection/pipeline/stage_03_model_training.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_03_model_training.py
      - src/DeepfakeDetection/components/model_training.py
      - config/config.yaml
      - artifacts/data_preprocessing/train
      - artifacts/data_preprocessing/val
    params:
      - input_shape
      - batch_size
      - sequence_length
      - num_workers
      - dropout_rate
      - units
      - learning_rate
      - epochs
      - lstm_layers
      - bidirectional
      - weight_decay
    outs:
      - artifacts/model_training/model.pt


  model_evaluation:
  
    cmd: python src/DeepfakeDetection/pipeline/stage_04_model_evaluation.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_04_model_evaluation.py
      - src/DeepfakeDetection/components/model_evaluation.py
      - config/config.yaml
      - artifacts/model_training/model.pt
      - artifacts/data_preprocessing/test

    params:
      - input_shape
      - batch_size
      - sequence_length
      - num_workers
    outs:
      - artifacts/model_evaluation/score.json
