stages:
  data_ingestion:
    cmd: python src/DeepfakeDetection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_01_data_ingestion.py
      - src/DeepfakeDetection/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/dfdc_train_part_0

  data_preprocessing:
    cmd: python src/DeepfakeDetection/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_02_data_preprocessing.py
      - src/DeepfakeDetection/components/data_preprocessing.py
      - config/config.yaml
      - artifacts/data_ingestion/dfdc_train_part_0
    params:
      - max_frames
      - target_size
      - scale_factor
      - min_neighbors
      - min_size
      - incremental_save_frequency
    outs:
      - artifacts/data_preprocessing/train/data/data.h5
      - artifacts/data_preprocessing/train/labels/labels.h5
      - artifacts/data_preprocessing/val/data/data.h5
      - artifacts/data_preprocessing/val/labels/labels.h5
      - artifacts/data_preprocessing/test/data/data.h5
      - artifacts/data_preprocessing/test/labels/labels.h5

  # model_training:
  #   cmd: python src/DeepfakeDetection/pipeline/stage_03_model_training.py
  #   deps:
  #     - src/DeepfakeDetection/pipeline/stage_03_model_training.py
  #     - src/DeepfakeDetection/components/model_training.py
  #     - config/config.yaml
  #     - artifacts/data_preprocessing/train/data/data.h5
  #     - artifacts/data_preprocessing/train/labels/labels.h5
  #     - artifacts/data_preprocessing/val/data/data.h5
  #     - artifacts/data_preprocessing/val/labels/labels.h5
  #   params:
  #     - input_shape
  #     - learning_rate
  #     - batch_size
  #     - epochs
  #   outs:
  #     - artifacts/model_training/cross_evit_model.h5

  # model_evaluation:
  #   cmd: python src/DeepfakeDetection/pipeline/stage_04_model_evaluation.py
  #   deps:
  #     - src/DeepfakeDetection/pipeline/stage_04_model_evaluation.py
  #     - src/DeepfakeDetection/components/model_evaluation.py
  #     - config/config.yaml
  #     - artifacts/model_training/cross_evit_model.h5
  #     - artifacts/data_preprocessing/test/data/data.h5
  #     - artifacts/data_preprocessing/test/labels/labels.h5
  #   outs:
  #     - artifacts/model_evaluation/score.json
