stages:
  data_ingestion:
    cmd: python src/DeepfakeDetection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_01_data_ingestion.py
      - src/DeepfakeDetection/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data

  data_preprocessing:
    cmd: python src/DeepfakeDetection/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_02_data_preprocessing.py
      - src/DeepfakeDetection/components/data_preprocessing.py
      - config/config.yaml
      - artifacts/data_ingestion/data
    params:
      - max_frames
      - target_size
      - scale_factor
      - min_neighbors
      - min_size
    outs:
      - artifacts/data_preprocessing/train
      - artifacts/data_preprocessing/test
      - artifacts/data_preprocessing/val

  model_training:
    cmd: python src/DeepfakeDetection/pipeline/stage_03_model_training.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_03_model_training.py
      - src/DeepfakeDetection/components/model_training.py
      - config/config.yaml
      - artifacts/data_preprocessing/train/data/data.h5
      - artifacts/data_preprocessing/train/labels/labels.h5
      - artifacts/data_preprocessing/val/data/data.h5
      - artifacts/data_preprocessing/val/labels/labels.h5
    params:
      - const_lr
      - input_shape
      - initial_learning_rate
      - learning_rate_decay
      - decay_steps
      - decay_rate
      - batch_size
      - epochs
      - pretrained
      - pretrained_top
      - include_top
      - units
      - activation
      - dropout_rate
      - l2
      - rotation
      - zoom
      - contrast
      - buffer
      - gnoise
    outs:
      - artifacts/model_training/model.h5

  model_evaluation:
    cmd: python src/DeepfakeDetection/pipeline/stage_04_model_evaluation.py
    deps:
      - src/DeepfakeDetection/pipeline/stage_04_model_evaluation.py
      - src/DeepfakeDetection/components/model_evaluation.py
      - config/config.yaml
      - artifacts/model_training/model.h5
      - artifacts/data_preprocessing/test/data/data.h5
      - artifacts/data_preprocessing/test/labels/labels.h5

    params:
      - threshold
    outs:
      - artifacts/model_evaluation/score.json
