# preprocessing
max_frames: 100
scene_change_threshold: 0.02
target_size: [224, 224]
scale_factor: 1.1
min_neighbors: 5
min_size: [30,30]

# training
input_shape: [224, 224, 3]
initial_learning_rate: 0.001
learning_rate_decay: 0.9
decay_steps: 10000
decay_rate: 0.9
batch_size: 16
epochs: 10
pretrained: False
pretrained_top: False
include_top: False
units: 256
activation: relu
dropout_rate: 0.5
l2: 0.01
rotation: 0.1
zoom: 0.1

#evaluation
threshold: 0.8