# data ingestion
num_videos: 1200

# preprocessing
fps: 30
max_frames: 150
resolution: [112, 112]

# training and evaluation
const_lr: False
input_shape: [260, 260, 3]
initial_learning_rate: 0.0001
learning_rate_decay: 0.001
decay_steps: 5000
decay_rate: 0.9
batch_size: 4
epochs: 20
pretrained: False
num_heads: 8
key_dim: 512
units: 512
activation: relu
dropout_rate: 0.2
l2: 0.02
attention_depth: 6
threshold: 0.5
buffer: 800
