# data ingestion
num_videos: 1200

# preprocessing
fps: 30
max_frames: 200
resolution: [224, 224]
expansion_factor: 0.2

# training and evaluation
input_shape: [224, 224, 3]
batch_size: 12
sequence_length: 10  
num_workers: 4
dropout_rate: 0.5  
units: 2048
learning_rate: 0.0001
epochs: 200
lstm_layers: 1
bidirectional: True
weight_decay: 0.00001