# data ingestion
num_videos: 1200

# preprocessing
fps: 30
max_frames: 150
resolution: [112, 112]

# training and evaluation
input_shape: [224, 224, 3]
batch_size: 4
sequence_length: 100
num_workers: 4
dropout_rate: 0.5
units: 512
learning_rate: 0.0001
epochs: 20

