# data ingestion
num_videos: 400

# preprocessing
mtcnn_thres: [0.95, 0.95, 0.95]
max_frames: 100
scene_change_threshold: 0.05
target_size: [224, 224]
scale_factor: 1.1
min_neighbors: 5
min_size: [30,30]

# training and evaluation
const_lr: True
input_shape: [224, 224, 3]
initial_learning_rate: 0.000001
learning_rate_decay: 0.9
decay_steps: 5000
decay_rate: 0.9
batch_size: 16
epochs: 500
pretrained: False
num_heads: 8
key_dim: 512
units: 512
activation: relu
dropout_rate: 0.3
l2: 0.03
buffer: 1000
attention_depth: 4
threshold: 0.5
