# preprocessing
max_frames: 100
scene_change_threshold: 0.02
target_size: [224, 224]
scale_factor: 1.1
min_neighbors: 5
min_size: [30,30]

# training
input_shape: [224, 224, 3]
learning_rate: 0.001
batch_size: 16
epochs: 5
pretrained: True
pretrained_top: False
include_top: False
units: 256
activation: relu
dropout_rate: 0.3