artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data: /home/sanskar-modi/FaceForensics++
  final_data_path: artifacts/data_ingestion/data

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_ingestion/data
  output_data: artifacts/data_preprocessing/

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_preprocessing/train/data/data.h5
  train_labels_path: artifacts/data_preprocessing/train/labels/labels.h5
  val_data_path: artifacts/data_preprocessing/val/data/data.h5
  val_labels_path: artifacts/data_preprocessing/val/labels/labels.h5
  model_path: artifacts/model_training/model.h5

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_preprocessing/test/data/data.h5
  labels_path: artifacts/data_preprocessing/test/labels/labels.h5
  model_path: artifacts/model_training/model.h5
  score: artifacts/model_evaluation/score.json
