artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1eRD9vs6lOwlNgngrsmX1lZapNsYIFVfV/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_ingestion/dfdc_train_part_0
  output_dir: artifacts/data_preprocessing

model_training:
  root_dir: artifacts/model_training
  train_data_path: artifacts/data_preprocessing/train/data/data.h5
  train_labels_path: artifacts/data_preprocessing/train/labels/labels.h5
  val_data_path: artifacts/data_preprocessing/val/data/data.h5
  val_labels_path: artifacts/data_preprocessing/val/labels/labels.h5
  model_path: artifacts/model_training/cross_evit_model.h5

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_preprocessing/test/data/data.h5
  labels_path: artifacts/data_preprocessing/test/labels/labels.h5
  model_path: artifacts/model_training/cross_evit_model.h5
  score: artifacts/model_evaluation/score.json
