artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data: /home/sanskar-modi/FaceForensics++
  final_data_path: artifacts/data_ingestion/data

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  data_path: artifacts/data_ingestion/data
  output_data: artifacts/data_preprocessing/

model_training:
  root_dir: artifacts/model_training
  data_path: artifacts/data_preprocessing
  model_path: artifacts/model_training/model.pt

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_preprocessing/test
  model_path: artifacts/model_training/model.pt
  score: artifacts/model_evaluation/score.json
